sonar.projectKey=charityconnect
sonar.projectName=CharityConnect
sonar.sources=frontend/src,backend/identity/src,backend/campaign/src,backend/donation/app
sonar.tests=backend/identity/test,backend/campaign/test,backend/donation/tests
sonar.javascript.lcov.reportPaths=backend/identity/coverage/lcov.info,backend/campaign/coverage/lcov.info,frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=backend/donation/coverage.xml
sonar.coverage.exclusions=**/*.config.*,**/main.tsx
