import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarCheck, Plus, Trash2, WalletCards } from "lucide-react";
import { useEffect, useState } from "react";
import { api, formatVnd } from "../../lib/api";
import type { Campaign, FinancialPlan } from "../../types";

interface EditableBudget { label: string; planned_amount: number }
interface EditableMilestone { id?: string; title: string; description: string; target_date: string; target_amount: number; status?: string }
export function FinancialPlanManager({ campaigns }: { campaigns: Campaign[] }): JSX.Element {
  const editable = campaigns.filter((item) => ["DRAFT", "REJECTED"].includes(item.status)); const [campaignId, setCampaignId] = useState(editable[0]?.id ?? campaigns[0]?.id ?? ""); const client = useQueryClient();
  const selected = campaigns.find((item) => item.id === campaignId); const plan = useQuery({ queryKey: ["financial-plan", campaignId], queryFn: () => api<FinancialPlan>(`/campaigns/${campaignId}/financial-plan`), enabled: Boolean(campaignId), retry: false });
  const [budgets, setBudgets] = useState<EditableBudget[]>([]); const [milestones, setMilestones] = useState<EditableMilestone[]>([]);
  useEffect(() => { if (!plan.data) return; setBudgets(plan.data.budget_items.map(({ label, planned_amount }) => ({ label, planned_amount }))); setMilestones(plan.data.milestones.map((item) => ({ ...item, target_date: item.target_date.slice(0, 10) }))); }, [plan.data]);
  const save = useMutation({ mutationFn: () => api(`/organization/campaigns/${campaignId}/financial-plan`, { method: "PUT", body: JSON.stringify({ budget_items: budgets, milestones }) }), onSuccess: () => { void client.invalidateQueries({ queryKey: ["financial-plan", campaignId] }); }, });
  const milestoneStatus = useMutation({ mutationFn: ({ id, status }: { id: string; status: "IN_PROGRESS" | "SUBMITTED" }) => api(`/organization/campaigns/${campaignId}/milestones/${id}/status`, { method: "PATCH", body: JSON.stringify({ status }) }), onSuccess: () => void client.invalidateQueries({ queryKey: ["financial-plan", campaignId] }) });
  const budgetTotal = budgets.reduce((sum, item) => sum + Number(item.planned_amount || 0), 0); const canEdit = Boolean(selected && ["DRAFT", "REJECTED"].includes(selected.status));
  return <section className="card overflow-hidden"><div className="border-b border-ink/10 p-5 sm:p-6"><div className="flex items-center gap-3"><WalletCards className="text-brand-700" /><div><h2 className="text-xl font-black">Ngân sách & mốc giải ngân</h2><p className="text-sm text-slate-500">Tổng ngân sách phải đúng bằng mục tiêu trước khi nộp duyệt.</p></div></div><select className="input mt-5" value={campaignId} onChange={(event) => setCampaignId(event.target.value)}>{campaigns.map((campaign) => <option value={campaign.id} key={campaign.id}>{campaign.title} · {campaign.status}</option>)}</select></div>
    {!campaignId ? <p className="p-6 text-sm text-slate-500">Tạo chiến dịch để lập kế hoạch tài chính.</p> : <div className="grid gap-0 xl:grid-cols-2"><div className="border-b border-ink/10 p-5 xl:border-b-0 xl:border-r sm:p-6"><div className="flex items-center justify-between"><h3 className="font-black">Hạng mục ngân sách</h3>{canEdit && <button className="rounded-lg p-2 hover:bg-sage-100" aria-label="Thêm ngân sách" onClick={() => setBudgets([...budgets, { label: "", planned_amount: 0 }])}><Plus /></button>}</div><div className="mt-4 space-y-3">{budgets.map((item, index) => <div className="grid grid-cols-[minmax(0,1fr)_130px_40px] gap-2" key={index}><input className="input" aria-label={`Tên ngân sách ${index + 1}`} disabled={!canEdit} value={item.label} onChange={(event) => setBudgets(budgets.map((value, at) => at === index ? { ...value, label: event.target.value } : value))} /><input className="input" aria-label={`Số tiền ngân sách ${index + 1}`} disabled={!canEdit} type="number" min="1" value={item.planned_amount} onChange={(event) => setBudgets(budgets.map((value, at) => at === index ? { ...value, planned_amount: Number(event.target.value) } : value))} />{canEdit ? <button className="grid h-12 place-items-center rounded-xl text-rose-600 hover:bg-rose-50" aria-label="Xóa hạng mục" onClick={() => setBudgets(budgets.filter((_, at) => at !== index))}><Trash2 size={18} /></button> : <span />}</div>)}</div><div className={`mt-4 rounded-xl p-3 text-sm font-bold ${budgetTotal === selected?.goal_amount ? "bg-brand-50 text-brand-800" : "bg-amber-50 text-amber-800"}`}>Tổng {formatVnd(budgetTotal)} / mục tiêu {formatVnd(selected?.goal_amount ?? 0)}</div></div>
      <div className="p-5 sm:p-6"><div className="flex items-center justify-between"><h3 className="font-black">Các mốc thực hiện</h3>{canEdit && <button className="rounded-lg p-2 hover:bg-sage-100" aria-label="Thêm mốc" onClick={() => setMilestones([...milestones, { title: "", description: "", target_date: new Date().toISOString().slice(0, 10), target_amount: 0 }])}><Plus /></button>}</div><div className="mt-4 space-y-4">{milestones.map((item, index) => <article className="rounded-2xl border border-ink/10 p-4" key={item.id ?? index}><div className="flex items-center gap-2"><CalendarCheck size={17} className="text-brand-700" /><input className="min-w-0 flex-1 bg-transparent font-bold outline-none" disabled={!canEdit} value={item.title} placeholder="Tên mốc" onChange={(event) => setMilestones(milestones.map((value, at) => at === index ? { ...value, title: event.target.value } : value))} />{item.status && <span className="text-[10px] font-black">{item.status}</span>}</div><textarea className="input mt-3 min-h-20" disabled={!canEdit} value={item.description} placeholder="Mô tả kết quả" onChange={(event) => setMilestones(milestones.map((value, at) => at === index ? { ...value, description: event.target.value } : value))} /><div className="mt-2 grid gap-2 sm:grid-cols-2"><input className="input" disabled={!canEdit} type="date" value={item.target_date} onChange={(event) => setMilestones(milestones.map((value, at) => at === index ? { ...value, target_date: event.target.value } : value))} /><input className="input" disabled={!canEdit} type="number" min="1" value={item.target_amount} onChange={(event) => setMilestones(milestones.map((value, at) => at === index ? { ...value, target_amount: Number(event.target.value) } : value))} /></div>{!canEdit && item.id && item.status === "PLANNED" && <button className="btn-secondary mt-3 !min-h-10" onClick={() => milestoneStatus.mutate({ id: item.id!, status: "IN_PROGRESS" })}>Bắt đầu mốc</button>}{!canEdit && item.id && item.status === "IN_PROGRESS" && <button className="btn-secondary mt-3 !min-h-10" onClick={() => milestoneStatus.mutate({ id: item.id!, status: "SUBMITTED" })}>Gửi báo cáo</button>}</article>)}</div></div></div>}
    {canEdit && <div className="border-t border-ink/10 p-5 text-right"><button className="btn-primary" disabled={save.isPending || budgetTotal !== selected?.goal_amount || !budgets.length || !milestones.length} onClick={() => save.mutate()}>{save.isPending ? "Đang lưu…" : "Lưu kế hoạch tài chính"}</button>{save.isError && <p className="mt-2 text-sm text-rose-700">{save.error.message}</p>}</div>}
  </section>;
}
