import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, BadgeCheck, CalendarDays, FileCheck2, ShieldCheck } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { useAuth } from "../auth/AuthContext";
import { CampaignPreferenceButtons } from "../features/engagement/CampaignPreferenceButtons";
import { api, formatVnd } from "../lib/api";
import type { Campaign, CampaignEscrow, FinancialPlan, ImpactReport } from "../types";

export function CampaignDetailPage(): JSX.Element {
  const { id = "" } = useParams(); const { user } = useAuth();
  const campaign = useQuery({ queryKey: ["campaign", id], queryFn: () => api<Campaign>(`/campaigns/${id}`), enabled: Boolean(id) });
  const reports = useQuery({ queryKey: ["public-impact-reports", id], queryFn: () => api<ImpactReport[]>(`/campaigns/${id}/impact-reports`), enabled: Boolean(id) });
  const escrow = useQuery({ queryKey: ["campaign-contract", id], queryFn: () => api<CampaignEscrow>(`/campaigns/${id}/contract`), enabled: Boolean(id), retry: false });
  const financialPlan = useQuery({ queryKey: ["financial-plan", id], queryFn: () => api<FinancialPlan>(`/campaigns/${id}/financial-plan`), enabled: Boolean(id), retry: false });
  if (campaign.isLoading) return <div className="container-page py-12"><div className="skeleton h-[520px]" /></div>;
  if (!campaign.data) return <div className="container-page py-12"><div className="card p-8">Không tìm thấy chiến dịch.</div></div>;
  const item = campaign.data; const percent = Math.min(100, Math.round(item.raised_amount / item.goal_amount * 100));
  const daysLeft = Math.max(0, Math.ceil((new Date(item.end_date).getTime() - Date.now()) / 86_400_000));
  const amountUsed = reports.data?.reduce((sum, report) => sum + report.amount_used, 0) ?? 0;
  return <div className="container-page py-8 lg:py-12">
    <Link className="inline-flex min-h-11 items-center gap-2 text-sm font-bold text-slate-600 hover:text-brand-700" to="/"><ArrowLeft size={17} /> Tất cả chiến dịch</Link>
    <div className="mt-5 grid gap-8 lg:grid-cols-[minmax(0,1fr)_380px]">
      <article><img className="aspect-[16/9] w-full rounded-[1.75rem] object-cover" src={item.image_url ?? "/images/community.jpg"} alt={item.title} /><div className="px-1 py-8 sm:px-4"><p className="eyebrow !bg-brand-50">{item.category}</p><h1 className="mt-5 max-w-3xl text-4xl font-black leading-tight tracking-[-0.04em] text-ink sm:text-5xl">{item.title}</h1><p className="mt-5 text-xl leading-8 text-slate-600">{item.summary}</p><div className="my-8 flex flex-wrap gap-4 border-y border-ink/10 py-5 text-sm font-semibold text-slate-700"><span className="flex items-center gap-2"><BadgeCheck className="text-brand-700" size={19} />{item.organization_name}</span><span className="flex items-center gap-2"><CalendarDays size={18} />Còn {daysLeft} ngày</span></div><div className="whitespace-pre-wrap text-[1.05rem] leading-8 text-slate-700">{item.description}</div>
        {financialPlan.data && <FinancialPlanSection plan={financialPlan.data} />}
        <section className="mt-12 border-t border-slate-200 pt-9"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-brand-50 text-brand-800"><FileCheck2 /></span><div><h2 className="text-2xl font-black">Timeline tác động</h2><p className="text-sm text-slate-500">Chỉ công khai báo cáo và bằng chứng đã được quản trị viên xác minh.</p></div></div><div className="mt-7 space-y-5">{reports.data?.map((report) => <article className="relative ml-5 border-l-2 border-brand-200 pb-3 pl-7" key={report.id}><span className="absolute -left-[9px] top-0 h-4 w-4 rounded-full border-4 border-white bg-brand-600" /><div className="flex flex-wrap items-center gap-2 text-sm"><time className="font-bold text-brand-800">{new Date(report.report_date).toLocaleDateString("vi-VN")}</time><span className="rounded-full bg-brand-50 px-2 py-1 text-xs font-black text-brand-800">ĐÃ XÁC MINH</span></div><h3 className="mt-2 text-lg font-black">{report.title}</h3><p className="mt-2 leading-7 text-slate-600">{report.description}</p><p className="mt-3 font-black text-ink">Đã sử dụng {formatVnd(report.amount_used)}</p><div className="mt-3 flex flex-wrap gap-2">{report.evidence.map((file) => <a className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold hover:border-brand-500" href={file.url} target="_blank" rel="noreferrer" key={file.id}>{file.original_name} · SHA {file.sha256.slice(0, 8)}…</a>)}</div></article>)}{reports.data?.length === 0 && <p className="rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">Chiến dịch chưa có báo cáo sử dụng quỹ được duyệt.</p>}</div></section>
      </div></article>
      <aside className="card h-fit p-5 sm:p-6 lg:sticky lg:top-28"><p className="text-sm font-semibold text-slate-500">Đã quyên góp</p><p className="mt-1 text-3xl font-black tracking-tight text-ink">{formatVnd(item.raised_amount)}</p><div className="mt-5 h-3 overflow-hidden rounded-full bg-sage-200"><div className="h-full rounded-full bg-brand-500" style={{ width: `${percent}%` }} /></div><div className="mt-3 flex justify-between gap-3 text-sm text-slate-600"><span><strong className="text-ink">{percent}%</strong> mục tiêu</span><span>{formatVnd(item.goal_amount)}</span></div>
        <div className="mt-5 grid grid-cols-2 gap-3 rounded-2xl bg-slate-50 p-4 text-sm"><div><p className="text-slate-500">Đã sử dụng</p><p className="mt-1 font-black">{formatVnd(amountUsed)}</p></div><div><p className="text-slate-500">Số dư minh bạch</p><p className="mt-1 font-black text-brand-800">{formatVnd(Math.max(0, item.raised_amount - amountUsed))}</p></div></div>
        {escrow.data && <div className="mt-4 rounded-2xl border border-slate-200 p-4"><div className="flex items-center justify-between gap-3"><p className="text-sm font-black">Escrow mô phỏng</p><span className="rounded-full bg-amber-100 px-2 py-1 text-[10px] font-black text-amber-900">{escrow.data.contract_state}</span></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><p className="text-slate-500">Đang khóa</p><p className="mt-1 font-black text-amber-700">{formatVnd(escrow.data.locked_amount)}</p></div><div><p className="text-slate-500">Đã giải ngân</p><p className="mt-1 font-black text-brand-800">{formatVnd(escrow.data.released_amount)}</p></div></div><p className="mt-3 text-xs leading-5 text-slate-500">State machine phục vụ demo; không giữ tiền thật.</p></div>}
        <div className="mt-4 rounded-2xl bg-sage-100 p-4"><p className="flex items-center gap-2 text-sm font-bold text-ink"><ShieldCheck className="text-brand-700" size={19} />Quyên góp có kiểm chứng</p><p className="mt-2 text-xs leading-5 text-slate-600">Biên nhận, hash-chain và Merkle Proof công khai.</p></div><div className="mt-4"><CampaignPreferenceButtons campaignId={id} /></div>{user?.role === "DONOR" ? <Link className="btn-primary mt-3 w-full" to={`/chien-dich/${id}/quyen-gop`}>Quyên góp ngay</Link> : !user ? <Link className="btn-primary mt-3 w-full" to="/dang-nhap">Đăng nhập để quyên góp</Link> : <p className="mt-3 rounded-xl bg-slate-100 p-3 text-center text-sm font-bold text-slate-600">Chỉ tài khoản người quyên góp mới thực hiện giao dịch.</p>}<p className="mt-3 text-center text-xs text-slate-500">Không kết nối cổng thanh toán thật</p>
      </aside>
    </div>
  </div>;
}

function FinancialPlanSection({ plan }: { plan: FinancialPlan }): JSX.Element {
  return <section className="mt-12 border-t border-slate-200 pt-9"><h2 className="text-2xl font-black">Ngân sách & mốc giải ngân</h2><p className="mt-2 text-sm text-slate-500">Đối chiếu kế hoạch ban đầu với chi phí đã được xác minh.</p><div className="mt-6 grid gap-4 sm:grid-cols-2">{plan.budget_items.map((budget) => { const ratio = budget.planned_amount ? Math.min(100, Math.round(budget.actual_amount / budget.planned_amount * 100)) : 0; return <article className="rounded-2xl border border-ink/10 bg-white p-4" key={budget.id}><div className="flex justify-between gap-3"><strong>{budget.label}</strong><span className="text-sm text-slate-500">{ratio}%</span></div><div className="mt-3 h-2 rounded-full bg-sage-200"><div className="h-full rounded-full bg-brand-500" style={{ width: `${ratio}%` }} /></div><p className="mt-3 text-sm"><b>{formatVnd(budget.actual_amount)}</b> / {formatVnd(budget.planned_amount)}</p></article>; })}</div><div className="mt-6 space-y-3">{plan.milestones.map((milestone, index) => <article className="flex gap-4 rounded-2xl bg-sage-100 p-4" key={milestone.id}><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-ink text-xs font-black text-white">{index + 1}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{milestone.title}</strong><span className="rounded-full bg-white px-2 py-1 text-[10px] font-black">{milestone.status}</span></div><p className="mt-1 text-sm text-slate-600">{milestone.description}</p><p className="mt-2 text-xs font-semibold">{formatVnd(milestone.target_amount)} · {new Date(milestone.target_date).toLocaleDateString("vi-VN")}</p></div></article>)}</div></section>;
}
